package br.com.era.api.service;
import br.com.era.api.dto.EquipamentoDto;
import br.com.era.api.dto.MovimentacaoDto;
import br.com.era.api.exception.RecursoNaoEncontradoException;
import br.com.era.api.exception.RegraNegocioException;
import br.com.era.api.model.*;
import br.com.era.api.repository.EquipamentoRepository;
import br.com.era.api.repository.MovimentacaoRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.util.Comparator;
import java.util.List;
import java.util.Set;
@Service
public class EquipamentoService {
    private final EquipamentoRepository repository; private final MovimentacaoRepository movimentacoes; private final ObraService obras; private final FuncionarioService funcionarios; private final UsuarioService usuarios; private final InventarioHistoricoService inventarioHistorico;
    public EquipamentoService(EquipamentoRepository repository,MovimentacaoRepository movimentacoes,ObraService obras,FuncionarioService funcionarios,UsuarioService usuarios,InventarioHistoricoService inventarioHistorico){this.repository=repository;this.movimentacoes=movimentacoes;this.obras=obras;this.funcionarios=funcionarios;this.usuarios=usuarios;this.inventarioHistorico=inventarioHistorico;}
    @Transactional(readOnly=true) public List<EquipamentoDto.Resposta> listar(){return repository.findAll().stream().map(this::resposta).toList();}
    @Transactional(readOnly=true) public List<EquipamentoDto.Resposta> listarParaUsuario(String login){Usuario usuario=usuarios.buscarPorLogin(login);if(usuario.getPerfil()!=PerfilUsuario.TECNICO)return listar();Set<Long> permitidas=obras.idsPermitidos(login);return repository.findAll().stream().filter(e->(e.getObra()!=null&&permitidas.contains(e.getObra().getId()))||movimentacoes.findByEquipamentoIdOrderByDataMovimentacaoAscIdAsc(e.getId()).stream().anyMatch(m->obraPermitida(m,permitidas))).map(e->resposta(e,permitidas)).toList();}
    @Transactional(readOnly=true) public List<EquipamentoDto.ItemCatalogo> listarCatalogo(){return repository.findAll().stream().map(e->new EquipamentoDto.ItemCatalogo(e.getTipo(),e.getModelo(),e.getMedida(),CatalogoChave.criar(e.getTipo(),e.getModelo(),e.getMedida()))).distinct().sorted(Comparator.comparing(EquipamentoDto.ItemCatalogo::modelo,String.CASE_INSENSITIVE_ORDER)).toList();}
    @Transactional(readOnly=true) public List<EquipamentoDto.Resposta> listarDeposito(){return repository.findByObraIsNullOrderByModeloAsc().stream().map(this::resposta).toList();}
    @Transactional public EquipamentoDto.Resposta cadastrar(EquipamentoDto.Requisicao d){if(repository.existsBySerieIgnoreCase(d.serie()))throw new RegraNegocioException("Já existe equipamento com esta série.");Equipamento e=new Equipamento();e.setTipo(d.tipo());e.setModelo(d.modelo());e.setSerie(d.serie());e.setStatus(d.status());e.setMedida(d.medida());e.setQuantidade(d.quantidade()==null?1:d.quantidade());e.setControleQuantidade(d.controleQuantidade()==null?(e.getQuantidade()>1?"LOTE":"INDIVIDUAL"):d.controleQuantidade());e.setObservacoes(d.observacoes());e.setObra(obras.buscarOpcional(d.obraId()));e.setTecnico(d.tecnico()==null||d.tecnico().isBlank()?null:funcionarios.buscarPorNome(d.tecnico()));LocalDate entrada=d.dataEntrada()!=null?d.dataEntrada():(d.data()!=null?d.data():LocalDate.now());e.setDataEntrada(entrada);e.setDataSaida(d.dataSaida());repository.save(e);if(e.getObra()!=null)inventarioHistorico.registrar(e.getObra());return resposta(e);}
    @Transactional public EquipamentoDto.Resposta atualizar(Long id,EquipamentoDto.Requisicao d){Equipamento e=buscar(id);Obra obraAnterior=e.getObra();repository.findBySerieIgnoreCase(d.serie()).filter(outro->!outro.getId().equals(id)).ifPresent(outro->{throw new RegraNegocioException("Já existe equipamento com esta série.");});e.setTipo(d.tipo());e.setModelo(d.modelo());e.setSerie(d.serie());e.setStatus(d.status());e.setObra(obras.buscarOpcional(d.obraId()));e.setTecnico(d.tecnico()==null||d.tecnico().isBlank()?null:funcionarios.buscarPorNome(d.tecnico()));if(d.dataEntrada()!=null)e.setDataEntrada(d.dataEntrada());if(d.dataSaida()!=null)e.setDataSaida(d.dataSaida());registrarObrasAfetadas(obraAnterior,e.getObra());return resposta(e);}
    @Transactional public EquipamentoDto.Resposta movimentar(Long id,MovimentacaoDto.Requisicao d){Equipamento e=buscar(id);Obra origem=e.getObra();Obra destino=obras.buscarOpcional(d.obraId());Funcionario tecnico=d.tecnico()==null||d.tecnico().isBlank()?null:funcionarios.buscarPorNome(d.tecnico());Movimentacao m=novaMovimentacao(e,null,origem,destino,tecnico,d.status(),d.dataMovimentacao());movimentacoes.save(m);aplicarDestino(e,destino,tecnico,d.status(),d.dataMovimentacao());registrarObrasAfetadas(origem,destino);return resposta(e);}
    @Transactional(readOnly=true) public List<MovimentacaoDto.Resposta> historico(Long id){buscar(id);return movimentacoes.findByEquipamentoIdOrderByDataMovimentacaoAscIdAsc(id).stream().map(this::respostaMovimentacao).toList();}
    @Transactional(readOnly=true) public List<MovimentacaoDto.Resposta> historicoParaUsuario(Long id,String login){Usuario usuario=usuarios.buscarPorLogin(login);if(usuario.getPerfil()!=PerfilUsuario.TECNICO)return historico(id);Set<Long> permitidas=obras.idsPermitidos(login);Equipamento equipamento=buscar(id);List<Movimentacao> historico=movimentacoes.findByEquipamentoIdOrderByDataMovimentacaoAscIdAsc(id);boolean acessivel=(equipamento.getObra()!=null&&permitidas.contains(equipamento.getObra().getId()))||historico.stream().anyMatch(m->obraPermitida(m,permitidas));if(!acessivel)throw new RecursoNaoEncontradoException("Equipamento não encontrado.");return historico.stream().filter(m->obraPermitida(m,permitidas)).map(m->respostaMovimentacaoRestrita(m,permitidas)).toList();}
    @Transactional(readOnly=true) public List<MovimentacaoDto.Resposta> restringirHistoricoParaUsuario(List<Movimentacao> historico,String login){Usuario usuario=usuarios.buscarPorLogin(login);if(usuario.getPerfil()!=PerfilUsuario.TECNICO)return historico.stream().map(this::respostaMovimentacao).toList();Set<Long> permitidas=obras.idsPermitidos(login);return historico.stream().filter(m->obraPermitida(m,permitidas)).map(m->respostaMovimentacaoRestrita(m,permitidas)).toList();}
    @Transactional(readOnly=true) public Equipamento buscar(Long id){return repository.findById(id).orElseThrow(()->new RecursoNaoEncontradoException("Equipamento não encontrado."));}
    public Movimentacao novaMovimentacao(Equipamento e,Solicitacao s,Obra origem,Obra destino,Funcionario tecnico,String status,LocalDate data){Movimentacao m=new Movimentacao();m.setEquipamento(e);m.setSolicitacao(s);m.setObraOrigem(origem);m.setObraDestino(destino);m.setTecnico(tecnico);m.setStatus(status);m.setDataMovimentacao(data);return m;}
    public void aplicarDestino(Equipamento e,Obra destino,Funcionario tecnico,String status,LocalDate data){e.setObra(destino);e.setTecnico(destino==null?null:tecnico);e.setStatus(status);e.setDataSaida(data);e.setDataEntrada(data);}
    public MovimentacaoDto.Resposta respostaMovimentacao(Movimentacao m){return new MovimentacaoDto.Resposta(m.getId(),m.getEquipamento().getId(),m.getSolicitacao()==null?null:m.getSolicitacao().getId(),m.getObraOrigem()==null?null:m.getObraOrigem().getId(),m.getObraDestino()==null?null:m.getObraDestino().getId(),m.getObraOrigem()==null?"Depósito central":m.getObraOrigem().getNome(),m.getObraDestino()==null?"Depósito central":m.getObraDestino().getNome(),m.getTecnico()==null?null:m.getTecnico().getNome(),m.getStatus(),m.getDataMovimentacao(),m.getDataMovimentacao(),m.getDataMovimentacao());}
    public Equipamento criarLoteDerivado(Equipamento origem,int quantidade,Obra destino,Funcionario tecnico,String status,LocalDate data,Long solicitacaoId){Equipamento lote=new Equipamento();lote.setTipo(origem.getTipo());lote.setModelo(origem.getModelo());lote.setSerie(origem.getSerie()+"-M"+solicitacaoId);lote.setStatus(status);lote.setMedida(origem.getMedida());lote.setQuantidade(quantidade);lote.setQuantidadeReservada(0);lote.setControleQuantidade("LOTE");lote.setObservacoes(origem.getObservacoes());lote.setObra(destino);lote.setTecnico(destino==null?null:tecnico);lote.setDataEntrada(data);lote.setDataSaida(data);return repository.save(lote);}
    private EquipamentoDto.Resposta resposta(Equipamento e){return resposta(e,null);}
    private EquipamentoDto.Resposta resposta(Equipamento e,Set<Long> obrasPermitidas){List<MovimentacaoDto.Resposta> h=movimentacoes.findByEquipamentoIdOrderByDataMovimentacaoAscIdAsc(e.getId()).stream().filter(m->obrasPermitidas==null||obraPermitida(m,obrasPermitidas)).map(m->obrasPermitidas==null?respostaMovimentacao(m):respostaMovimentacaoRestrita(m,obrasPermitidas)).toList();boolean localPermitido=obrasPermitidas==null||(e.getObra()!=null&&obrasPermitidas.contains(e.getObra().getId()));return new EquipamentoDto.Resposta(e.getId(),e.getTipo(),e.getModelo(),e.getSerie(),e.getStatus(),localPermitido&&e.getObra()!=null?e.getObra().getId():null,localPermitido&&e.getTecnico()!=null?e.getTecnico().getNome():null,e.getDataEntrada(),e.getDataEntrada(),e.getDataSaida(),e.getDataSaida(),h,e.getMedida(),e.getQuantidade(),e.getQuantidadeReservada(),e.getQuantidadeDisponivel(),e.getObservacoes(),e.getControleQuantidade(),CatalogoChave.criar(e.getTipo(),e.getModelo(),e.getMedida()));}
    private MovimentacaoDto.Resposta respostaMovimentacaoRestrita(Movimentacao m,Set<Long> permitidas){Long origem=m.getObraOrigem()!=null&&permitidas.contains(m.getObraOrigem().getId())?m.getObraOrigem().getId():null;Long destino=m.getObraDestino()!=null&&permitidas.contains(m.getObraDestino().getId())?m.getObraDestino().getId():null;String origemNome=origem==null?"Local restrito":m.getObraOrigem().getNome();String destinoNome=destino==null?"Local restrito":m.getObraDestino().getNome();return new MovimentacaoDto.Resposta(m.getId(),m.getEquipamento().getId(),m.getSolicitacao()==null?null:m.getSolicitacao().getId(),origem,destino,origemNome,destinoNome,m.getTecnico()==null?null:m.getTecnico().getNome(),m.getStatus(),m.getDataMovimentacao(),m.getDataMovimentacao(),m.getDataMovimentacao());}
    private boolean obraPermitida(Movimentacao movimentacao,Set<Long> permitidas){Long origem=movimentacao.getObraOrigem()==null?null:movimentacao.getObraOrigem().getId();Long destino=movimentacao.getObraDestino()==null?null:movimentacao.getObraDestino().getId();return permitidas.contains(origem)||permitidas.contains(destino);}
    private void registrarObrasAfetadas(Obra origem,Obra destino){if(origem!=null)inventarioHistorico.registrar(origem);if(destino!=null&&(origem==null||!destino.getId().equals(origem.getId())))inventarioHistorico.registrar(destino);}
}
