package br.com.era.api.service;
import br.com.era.api.dto.SolicitacaoDto;
import br.com.era.api.exception.RecursoNaoEncontradoException;
import br.com.era.api.exception.RegraNegocioException;
import br.com.era.api.model.*;
import br.com.era.api.repository.EquipamentoRepository;
import br.com.era.api.repository.MovimentacaoRepository;
import br.com.era.api.repository.SolicitacaoRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
@Service
public class SolicitacaoService {
    private final SolicitacaoRepository repository; private final EquipamentoRepository equipamentos; private final MovimentacaoRepository movimentacoes; private final ObraService obras; private final FuncionarioService funcionarios; private final EquipamentoService equipamentoService; private final UsuarioService usuarios; private final CautelaService cautelas; private final InventarioHistoricoService inventarioHistorico;
    public SolicitacaoService(SolicitacaoRepository repository,EquipamentoRepository equipamentos,MovimentacaoRepository movimentacoes,ObraService obras,FuncionarioService funcionarios,EquipamentoService equipamentoService,UsuarioService usuarios,CautelaService cautelas,InventarioHistoricoService inventarioHistorico){this.repository=repository;this.equipamentos=equipamentos;this.movimentacoes=movimentacoes;this.obras=obras;this.funcionarios=funcionarios;this.equipamentoService=equipamentoService;this.usuarios=usuarios;this.cautelas=cautelas;this.inventarioHistorico=inventarioHistorico;}
    @Transactional(readOnly=true) public List<SolicitacaoDto.Resposta> listar(){return repository.findAll().stream().filter(s->"Movimentação".equals(s.getTipo())).map(this::resposta).toList();}
    @Transactional(readOnly=true) public List<SolicitacaoDto.Resposta> listarParaUsuario(String login){Usuario usuario=usuarios.buscarPorLogin(login);if(usuario.getPerfil()!=PerfilUsuario.TECNICO)return listar();if(usuario.getFuncionario()==null)throw new RegraNegocioException("O usuário técnico precisa estar vinculado a um funcionário.");Set<Long> permitidas=obras.idsPermitidos(login);return repository.findByTecnicoIdOrderByCriadoEmDesc(usuario.getFuncionario().getId()).stream().filter(s->"Movimentação".equals(s.getTipo())).map(s->respostaTecnico(s,permitidas)).toList();}
    @Transactional public SolicitacaoDto.Resposta cadastrar(SolicitacaoDto.Requisicao d,String login){Usuario usuario=usuarios.buscarPorLogin(login);Funcionario tecnico;if(usuario.getPerfil()==PerfilUsuario.TECNICO){if(usuario.getFuncionario()==null)throw new RegraNegocioException("O usuário técnico precisa estar vinculado a um funcionário.");obras.validarAcessoTecnico(usuario,d.obraOrigemId());obras.validarAcessoTecnico(usuario,d.obraDestinoId());tecnico=usuario.getFuncionario();}else{tecnico=funcionarios.buscarPorNome(d.tecnico());}Solicitacao s=new Solicitacao();s.setTipo("Movimentação");s.setStatus("Pendente");s.setTecnico(tecnico);s.setSolicitante(usuario.getPerfil()==PerfilUsuario.TECNICO?tecnico:funcionarios.buscarPorNome(d.solicitante()==null||d.solicitante().isBlank()?d.tecnico():d.solicitante()));s.setObraOrigem(obras.buscarOpcional(d.obraOrigemId()));s.setObraDestino(obras.buscarOpcional(d.obraDestinoId()));s.setDataSolicitacao(d.dataSolicitacao());s.setObservacao(d.observacao());s.substituirMateriais(criarMateriais(d.materiais()));boolean pedidoSemOrigem=usuario.getPerfil()==PerfilUsuario.TECNICO&&d.obraOrigemId()==null&&d.obraDestinoId()!=null;if(pedidoSemOrigem){if(s.getMateriais().stream().anyMatch(m->m.getIdentificacao()!=null&&!m.getIdentificacao().isBlank()))throw new RegraNegocioException("Solicite o material sem informar série ou localização.");}else{reservarMateriais(s);}Solicitacao salva=repository.save(s);return usuario.getPerfil()==PerfilUsuario.TECNICO?respostaTecnico(salva,obras.idsPermitidos(login)):resposta(salva);}
    @Transactional public SolicitacaoDto.Resposta atualizar(Long id,SolicitacaoDto.Atualizacao d){Solicitacao s=buscar(id);if(!Set.of("Pendente","Aprovada").contains(s.getStatus()))throw new RegraNegocioException("Somente movimentações pendentes ou aprovadas podem ser editadas.");if(d.materiais()!=null&&(d.materiais().isEmpty()||d.materiais().stream().anyMatch(m->m.identificacao()==null||m.identificacao().isBlank())))throw new RegraNegocioException("Selecione ao menos um item disponível no estoque.");if(d.materiais()!=null)liberarReservas(s);if(d.tecnico()!=null)s.setTecnico(funcionarios.buscarPorNome(d.tecnico()));s.setObraOrigem(obras.buscarOpcional(d.obraOrigemId()));s.setObraDestino(obras.buscarOpcional(d.obraDestinoId()));if(d.observacao()!=null)s.setObservacao(d.observacao());if(d.materiais()!=null)s.substituirMateriais(criarMateriais(d.materiais()));if(d.materiais()!=null)reservarMateriais(s);return resposta(s);}
    @Transactional public SolicitacaoDto.Resposta aprovar(Long id,String login){Solicitacao s=buscar(id);if(!"Pendente".equals(s.getStatus()))throw new RegraNegocioException("A solicitação já foi analisada.");s.setStatus(s.getObraDestino()==null?"Aguardando coleta":"Aprovada");s.setDataDecisao(LocalDate.now());if("Aguardando coleta".equals(s.getStatus())){if(s.getMateriais().stream().anyMatch(m->m.getIdentificacao()==null||m.getIdentificacao().isBlank()))throw new RegraNegocioException("Defina os equipamentos antes de aprovar a retirada.");cautelas.emitir(s,login);}return resposta(s);}
    @Transactional public SolicitacaoDto.Resposta rejeitar(Long id){Solicitacao s=buscar(id);if(!"Pendente".equals(s.getStatus()))throw new RegraNegocioException("A solicitação já foi analisada.");liberarReservas(s);s.setStatus("Rejeitada");s.setDataDecisao(LocalDate.now());return resposta(s);}
    @Transactional public SolicitacaoDto.Resposta solicitarCompra(Long id,Long materialId,int quantidade){Solicitacao s=buscar(id);if(!"Aprovada".equals(s.getStatus()))throw new RegraNegocioException("A compra só pode ser solicitada para uma movimentação aprovada.");MaterialSolicitado material=s.getMateriais().stream().filter(m->m.getId().equals(materialId)).findFirst().orElseThrow(()->new RecursoNaoEncontradoException("Material não encontrado na solicitação."));if(material.getIdentificacao()!=null&&!material.getIdentificacao().isBlank())throw new RegraNegocioException("O material já possui equipamento definido.");if(quantidade>material.getQuantidade())throw new RegraNegocioException("A quantidade para compra não pode superar a quantidade solicitada.");material.solicitarCompra(quantidade);return resposta(s);}
    @Transactional public SolicitacaoDto.Resposta registrarAquisicao(Long id,Long materialId,int quantidade,String identificacao){Solicitacao s=buscar(id);MaterialSolicitado material=s.getMateriais().stream().filter(m->m.getId().equals(materialId)).findFirst().orElseThrow(()->new RecursoNaoEncontradoException("Material não encontrado na solicitação."));if(material.getQuantidadeCompra()<=0)throw new RegraNegocioException("Não existe compra solicitada para este material.");int saldoEntrada=material.getQuantidadeCompra()-material.getQuantidadeEntradaEstoque();if(quantidade>saldoEntrada)throw new RegraNegocioException("A quantidade para entrada não pode superar o saldo de "+saldoEntrada+" unidade(s).");int jaAdquiridoSemEntrada=material.getQuantidadeAdquirida()-material.getQuantidadeEntradaEstoque();int novaAquisicao=Math.max(0,quantidade-jaAdquiridoSemEntrada);equipamentoService.registrarEntradaCompra(material.getNome(),material.getCatalogoChave(),quantidade,identificacao,s.getId());if(novaAquisicao>0)material.registrarAquisicao(novaAquisicao);material.registrarEntradaEstoque(quantidade);return resposta(s);}
    @Transactional public List<SolicitacaoDto.Resposta> distribuir(Long id,SolicitacaoDto.Distribuicao dados){Solicitacao original=repository.buscarParaAtualizacao(id).filter(s->"Movimentação".equals(s.getTipo())).orElseThrow(()->new RecursoNaoEncontradoException("Movimentação não encontrada."));if(!"Aprovada".equals(original.getStatus()))throw new RegraNegocioException("Somente uma solicitação aprovada pode ser distribuída.");Map<String,Integer> solicitadas=agruparQuantidades(original.getMateriais().stream().map(m->new SolicitacaoDto.MaterialRequisicao(m.getNome(),m.getQuantidade(),m.getIdentificacao(),m.getCatalogoChave())).toList());List<SolicitacaoDto.MaterialRequisicao> selecionadas=dados.atendimentos().stream().flatMap(a->a.materiais().stream()).toList();if(!solicitadas.equals(agruparQuantidades(selecionadas)))throw new RegraNegocioException("As quantidades distribuídas precisam corresponder ao pedido original.");Set<Long> origens=new HashSet<>();for(SolicitacaoDto.AtendimentoOrigem atendimento:dados.atendimentos()){Long chave=atendimento.obraOrigemId()==null?Long.MIN_VALUE:atendimento.obraOrigemId();if(!origens.add(chave))throw new RegraNegocioException("Agrupe os materiais que saem da mesma origem.");}liberarReservas(original);Solicitacao raiz=original.getSolicitacaoPai()==null?original:original.getSolicitacaoPai();List<SolicitacaoDto.Resposta> respostas=new java.util.ArrayList<>();for(int indice=0;indice<dados.atendimentos().size();indice++){SolicitacaoDto.AtendimentoOrigem atendimento=dados.atendimentos().get(indice);Solicitacao destino=indice==0?original:copiarParaAtendimento(original,raiz);destino.setObraOrigem(obras.buscarOpcional(atendimento.obraOrigemId()));destino.substituirMateriais(criarMateriais(atendimento.materiais()));reservarMateriais(destino);if(indice>0)repository.save(destino);respostas.add(resposta(destino));}return respostas;}
    @Transactional public SolicitacaoDto.Resposta iniciarTransito(Long id,String login){Solicitacao s=buscar(id);validarInicioTransito(s,login);if(!Set.of("Aprovada","Aguardando coleta").contains(s.getStatus()))throw new RegraNegocioException("A movimentação ainda não pode iniciar o transporte.");if(s.getMateriais().stream().anyMatch(m->m.getIdentificacao()==null||m.getIdentificacao().isBlank()))throw new RegraNegocioException("O estoque precisa definir os equipamentos antes do envio.");s.setStatus("Em trânsito");s.setTransitoEm(OffsetDateTime.now());cautelas.emitir(s,login);return respostaParaUsuario(s,login);}
    @Transactional public SolicitacaoDto.Resposta concluir(Long id,String login){Solicitacao s=buscar(id);validarConclusao(s,login);if(!"Em trânsito".equals(s.getStatus()))throw new RegraNegocioException("A movimentação precisa estar em trânsito para confirmar o recebimento.");sincronizarMovimentacoes(s);if(s.getObraOrigem()!=null)inventarioHistorico.registrar(s.getObraOrigem());if(s.getObraDestino()!=null&&(s.getObraOrigem()==null||!s.getObraDestino().getId().equals(s.getObraOrigem().getId())))inventarioHistorico.registrar(s.getObraDestino());s.setStatus("Concluída");s.setConcluidaEm(OffsetDateTime.now());return respostaParaUsuario(s,login);}
    @Transactional(readOnly=true) public Solicitacao buscar(Long id){return repository.findById(id).filter(s->"Movimentação".equals(s.getTipo())).orElseThrow(()->new RecursoNaoEncontradoException("Movimentação não encontrada."));}
    private void sincronizarMovimentacoes(Solicitacao s){Set<Long> idsAtuais=new HashSet<>();Map<String,Integer> quantidadesPorSerie=new LinkedHashMap<>();Map<String,String> seriesOriginais=new LinkedHashMap<>();for(MaterialSolicitado material:s.getMateriais()){if(material.getIdentificacao()==null||material.getIdentificacao().isBlank())throw new RegraNegocioException("Todo equipamento movimentado precisa de identificação/série.");String chave=material.getIdentificacao().trim().toLowerCase();seriesOriginais.putIfAbsent(chave,material.getIdentificacao().trim());quantidadesPorSerie.merge(chave,material.getQuantidade(),Integer::sum);}for(Map.Entry<String,Integer> item:quantidadesPorSerie.entrySet()){String serie=seriesOriginais.get(item.getKey());Equipamento e=equipamentos.buscarPorSerieParaAtualizacao(serie).orElseThrow(()->new RecursoNaoEncontradoException("Equipamento não encontrado pela série: "+serie));int quantidade=item.getValue();if(e.getQuantidadeReservada()<quantidade)throw new RegraNegocioException("A reserva do item "+e.getModelo()+" não está mais disponível.");e.setQuantidadeReservada(e.getQuantidadeReservada()-quantidade);String status=s.getObraDestino()==null?"Em estoque":"Em campo";Equipamento movimentado=e;if(e.isLote()&&quantidade<e.getQuantidade()){e.setQuantidade(e.getQuantidade()-quantidade);movimentado=equipamentoService.criarLoteDerivado(e,quantidade,s.getObraDestino(),s.getTecnico(),status,s.getDataSolicitacao(),s.getId());}else{equipamentoService.aplicarDestino(e,s.getObraDestino(),s.getTecnico(),status,s.getDataSolicitacao());}Equipamento loteMovimentado=movimentado;idsAtuais.add(loteMovimentado.getId());Movimentacao m=movimentacoes.findBySolicitacaoIdAndEquipamentoId(s.getId(),loteMovimentado.getId()).orElseGet(()->equipamentoService.novaMovimentacao(loteMovimentado,s,s.getObraOrigem(),s.getObraDestino(),s.getTecnico(),status,s.getDataSolicitacao()));m.reativar();m.setObraOrigem(s.getObraOrigem());m.setObraDestino(s.getObraDestino());m.setTecnico(s.getTecnico());m.setStatus(status);m.setDataMovimentacao(s.getDataSolicitacao());movimentacoes.save(m);}
        for(Movimentacao removida:movimentacoes.findBySolicitacaoId(s.getId()))if(removida.isAtiva()&&!idsAtuais.contains(removida.getEquipamento().getId())){Equipamento e=removida.getEquipamento();equipamentoService.aplicarDestino(e,s.getObraOrigem(),null,s.getObraOrigem()==null?"Em estoque":"Em campo",s.getDataSolicitacao());removida.cancelar();}
    }
    private void reservarMateriais(Solicitacao s){for(MaterialSolicitado material:s.getMateriais()){if(material.getIdentificacao()==null||material.getIdentificacao().isBlank())throw new RegraNegocioException("Todo equipamento movimentado precisa de identificação/série.");Equipamento e=equipamentos.buscarPorSerieParaAtualizacao(material.getIdentificacao()).orElseThrow(()->new RecursoNaoEncontradoException("Equipamento não encontrado pela série: "+material.getIdentificacao()));Long obraAtual=e.getObra()==null?null:e.getObra().getId();Long obraOrigem=s.getObraOrigem()==null?null:s.getObraOrigem().getId();if(!Objects.equals(obraAtual,obraOrigem))throw new RegraNegocioException("O item "+e.getModelo()+" não está na origem informada.");if(!statusMovimentavel(e.getStatus()))throw new RegraNegocioException("O item "+e.getModelo()+" não está disponível para movimentação.");String chaveEquipamento=CatalogoChave.criar(e.getTipo(),e.getModelo(),e.getMedida());if(material.getCatalogoChave()!=null&&!material.getCatalogoChave().isBlank()&&!material.getCatalogoChave().equals(chaveEquipamento))throw new RegraNegocioException("O equipamento selecionado não corresponde ao material solicitado.");if(!e.isLote()&&material.getQuantidade()!=1)throw new RegraNegocioException("Ativos individuais devem ser movimentados uma unidade por vez.");if(material.getQuantidade()>e.getQuantidadeDisponivel())throw new RegraNegocioException("Quantidade indisponível para "+e.getModelo()+". Disponível: "+e.getQuantidadeDisponivel()+".");material.setNome(e.getModelo());e.setQuantidadeReservada(e.getQuantidadeReservada()+material.getQuantidade());}}
    private void liberarReservas(Solicitacao s){for(MaterialSolicitado material:s.getMateriais()){if(material.getIdentificacao()==null)continue;equipamentos.buscarPorSerieParaAtualizacao(material.getIdentificacao()).ifPresent(e->e.setQuantidadeReservada(Math.max(0,e.getQuantidadeReservada()-material.getQuantidade())));}}
    private void validarResponsavel(Solicitacao solicitacao,String login){Usuario usuario=usuarios.buscarPorLogin(login);if(usuario.getPerfil()==PerfilUsuario.TECNICO&&(usuario.getFuncionario()==null||!usuario.getFuncionario().getId().equals(solicitacao.getTecnico().getId())))throw new RegraNegocioException("Você não pode atualizar a movimentação de outro técnico.");}
    private void validarInicioTransito(Solicitacao s,String login){Usuario usuario=usuarios.buscarPorLogin(login);if(usuario.getPerfil()==PerfilUsuario.TECNICO)throw new RegraNegocioException("A retirada ou o envio deve ser confirmado pelo estoque.");if(s.getObraDestino()==null&&!Set.of(PerfilUsuario.ADMIN,PerfilUsuario.ESTOQUE).contains(usuario.getPerfil()))throw new RegraNegocioException("A retirada deve ser confirmada exclusivamente pelo estoque ou administrador.");}
    private void validarConclusao(Solicitacao s,String login){Usuario usuario=usuarios.buscarPorLogin(login);if(s.getObraDestino()!=null){if(usuario.getPerfil()!=PerfilUsuario.TECNICO)throw new RegraNegocioException("O recebimento na obra deve ser confirmado pelo técnico responsável.");validarResponsavel(s,login);return;}if(!Set.of(PerfilUsuario.ADMIN,PerfilUsuario.ESTOQUE).contains(usuario.getPerfil()))throw new RegraNegocioException("O retorno ao depósito deve ser confirmado pelo estoque ou administrador.");}
    private List<MaterialSolicitado> criarMateriais(List<SolicitacaoDto.MaterialRequisicao> itens){return itens.stream().map(i->new MaterialSolicitado(i.nome(),i.quantidade(),i.identificacao(),i.catalogoChave())).toList();}
    private Map<String,Integer> agruparQuantidades(List<SolicitacaoDto.MaterialRequisicao> materiais){Map<String,Integer> totais=new LinkedHashMap<>();for(SolicitacaoDto.MaterialRequisicao material:materiais){String chave=material.catalogoChave()==null||material.catalogoChave().isBlank()?CatalogoChave.normalizar(material.nome()):material.catalogoChave();totais.merge(chave,material.quantidade(),Integer::sum);}return totais;}
    private boolean statusMovimentavel(String status){String normalizado=CatalogoChave.normalizar(status);return Set.of("em estoque","em campo","disponivel").contains(normalizado);}
    private Solicitacao copiarParaAtendimento(Solicitacao base,Solicitacao raiz){Solicitacao copia=new Solicitacao();copia.setTipo(base.getTipo());copia.setStatus("Aprovada");copia.setSolicitante(base.getSolicitante());copia.setTecnico(base.getTecnico());copia.setObraDestino(base.getObraDestino());copia.setDataSolicitacao(base.getDataSolicitacao());copia.setDataDecisao(base.getDataDecisao());copia.setObservacao(base.getObservacao());copia.setSolicitacaoPai(raiz);return copia;}
    private SolicitacaoDto.Resposta resposta(Solicitacao s){return new SolicitacaoDto.Resposta(s.getId(),s.getSolicitacaoPai()==null?null:s.getSolicitacaoPai().getId(),s.getTipo(),s.getStatus(),s.getSolicitante().getNome(),s.getTecnico().getNome(),s.getObraOrigem()==null?null:s.getObraOrigem().getId(),s.getObraDestino()==null?null:s.getObraDestino().getId(),s.getDataSolicitacao(),s.getDataDecisao(),s.getTransitoEm(),s.getConcluidaEm(),s.getObservacao(),s.getMateriais().stream().map(this::respostaMaterial).toList());}
    private SolicitacaoDto.Resposta respostaParaUsuario(Solicitacao s,String login){Usuario usuario=usuarios.buscarPorLogin(login);return usuario.getPerfil()==PerfilUsuario.TECNICO?respostaTecnico(s,obras.idsPermitidos(login)):resposta(s);}
    private SolicitacaoDto.Resposta respostaTecnico(Solicitacao s,Set<Long> permitidas){Long origem=s.getObraOrigem()!=null&&permitidas.contains(s.getObraOrigem().getId())?s.getObraOrigem().getId():null;Long destino=s.getObraDestino()!=null&&permitidas.contains(s.getObraDestino().getId())?s.getObraDestino().getId():null;return new SolicitacaoDto.Resposta(s.getId(),s.getSolicitacaoPai()==null?null:s.getSolicitacaoPai().getId(),s.getTipo(),s.getStatus(),s.getSolicitante().getNome(),s.getTecnico().getNome(),origem,destino,s.getDataSolicitacao(),s.getDataDecisao(),s.getTransitoEm(),s.getConcluidaEm(),s.getObservacao(),s.getMateriais().stream().map(this::respostaMaterial).toList());}
    private SolicitacaoDto.MaterialResposta respostaMaterial(MaterialSolicitado m){return new SolicitacaoDto.MaterialResposta(m.getId(),m.getNome(),m.getQuantidade(),m.getIdentificacao(),m.getCatalogoChave(),m.getQuantidadeCompra(),m.getCompraSolicitadaEm(),m.getQuantidadeAdquirida(),m.getQuantidadeEntradaEstoque(),m.getAdquiridaEm());}
}
