package br.com.era.api.service;
import br.com.era.api.dto.SolicitacaoDto;
import br.com.era.api.exception.RecursoNaoEncontradoException;
import br.com.era.api.exception.RegraNegocioException;
import br.com.era.api.model.*;
import br.com.era.api.repository.EquipamentoRepository;
import br.com.era.api.repository.MovimentacaoRepository;
import br.com.era.api.repository.SolicitacaoRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
@Service
public class SolicitacaoService {
    private final SolicitacaoRepository repository; private final EquipamentoRepository equipamentos; private final MovimentacaoRepository movimentacoes; private final ObraService obras; private final FuncionarioService funcionarios; private final EquipamentoService equipamentoService; private final UsuarioService usuarios;
    public SolicitacaoService(SolicitacaoRepository repository,EquipamentoRepository equipamentos,MovimentacaoRepository movimentacoes,ObraService obras,FuncionarioService funcionarios,EquipamentoService equipamentoService,UsuarioService usuarios){this.repository=repository;this.equipamentos=equipamentos;this.movimentacoes=movimentacoes;this.obras=obras;this.funcionarios=funcionarios;this.equipamentoService=equipamentoService;this.usuarios=usuarios;}
    @Transactional(readOnly=true) public List<SolicitacaoDto.Resposta> listar(){return repository.findAll().stream().filter(s->"Movimentação".equals(s.getTipo())).map(this::resposta).toList();}
    @Transactional(readOnly=true) public List<SolicitacaoDto.Resposta> listarParaUsuario(String login){Usuario usuario=usuarios.buscarPorLogin(login);if(usuario.getPerfil()!=PerfilUsuario.TECNICO)return listar();if(usuario.getFuncionario()==null)throw new RegraNegocioException("O usuário técnico precisa estar vinculado a um funcionário.");return repository.findByTecnicoIdOrderByCriadoEmDesc(usuario.getFuncionario().getId()).stream().filter(s->"Movimentação".equals(s.getTipo())).map(this::resposta).toList();}
    @Transactional public SolicitacaoDto.Resposta cadastrar(SolicitacaoDto.Requisicao d,String login){Usuario usuario=usuarios.buscarPorLogin(login);Funcionario tecnico;if(usuario.getPerfil()==PerfilUsuario.TECNICO){if(usuario.getFuncionario()==null)throw new RegraNegocioException("O usuário técnico precisa estar vinculado a um funcionário.");tecnico=usuario.getFuncionario();}else{tecnico=funcionarios.buscarPorNome(d.tecnico());}Solicitacao s=new Solicitacao();s.setTipo("Movimentação");s.setStatus("Pendente");s.setTecnico(tecnico);s.setSolicitante(usuario.getPerfil()==PerfilUsuario.TECNICO?tecnico:funcionarios.buscarPorNome(d.solicitante()==null||d.solicitante().isBlank()?d.tecnico():d.solicitante()));s.setObraOrigem(obras.buscarOpcional(d.obraOrigemId()));s.setObraDestino(obras.buscarOpcional(d.obraDestinoId()));s.setDataSolicitacao(d.dataSolicitacao());s.setObservacao(d.observacao());s.substituirMateriais(criarMateriais(d.materiais()));reservarMateriais(s);return resposta(repository.save(s));}
    @Transactional public SolicitacaoDto.Resposta atualizar(Long id,SolicitacaoDto.Atualizacao d){Solicitacao s=buscar(id);if("Rejeitada".equals(s.getStatus()))throw new RegraNegocioException("Solicitações rejeitadas não podem ser editadas.");if("Pendente".equals(s.getStatus())&&d.materiais()!=null)liberarReservas(s);if(d.tecnico()!=null)s.setTecnico(funcionarios.buscarPorNome(d.tecnico()));s.setObraOrigem(obras.buscarOpcional(d.obraOrigemId()));s.setObraDestino(obras.buscarOpcional(d.obraDestinoId()));if(d.observacao()!=null)s.setObservacao(d.observacao());if(d.materiais()!=null)s.substituirMateriais(criarMateriais(d.materiais()));if("Pendente".equals(s.getStatus())&&d.materiais()!=null)reservarMateriais(s);if("Aprovada".equals(s.getStatus()))sincronizarMovimentacoes(s);return resposta(s);}
    @Transactional public SolicitacaoDto.Resposta aprovar(Long id){Solicitacao s=buscar(id);if(!"Pendente".equals(s.getStatus()))throw new RegraNegocioException("A solicitação já foi analisada.");sincronizarMovimentacoes(s);s.setStatus("Aprovada");s.setDataDecisao(LocalDate.now());return resposta(s);}
    @Transactional public SolicitacaoDto.Resposta rejeitar(Long id){Solicitacao s=buscar(id);if(!"Pendente".equals(s.getStatus()))throw new RegraNegocioException("A solicitação já foi analisada.");liberarReservas(s);s.setStatus("Rejeitada");s.setDataDecisao(LocalDate.now());return resposta(s);}
    @Transactional(readOnly=true) public Solicitacao buscar(Long id){return repository.findById(id).filter(s->"Movimentação".equals(s.getTipo())).orElseThrow(()->new RecursoNaoEncontradoException("Movimentação não encontrada."));}
    private void sincronizarMovimentacoes(Solicitacao s){Set<Long> idsAtuais=new HashSet<>();for(MaterialSolicitado material:s.getMateriais()){if(material.getIdentificacao()==null||material.getIdentificacao().isBlank())throw new RegraNegocioException("Todo equipamento movimentado precisa de identificação/série.");Equipamento e=equipamentos.buscarPorSerieParaAtualizacao(material.getIdentificacao()).orElseThrow(()->new RecursoNaoEncontradoException("Equipamento não encontrado pela série: "+material.getIdentificacao()));int quantidade=material.getQuantidade();if(e.getQuantidadeReservada()<quantidade)throw new RegraNegocioException("A reserva do item "+e.getModelo()+" não está mais disponível.");e.setQuantidadeReservada(e.getQuantidadeReservada()-quantidade);String status=s.getObraDestino()==null?"Em estoque":"Em campo";Equipamento movimentado=e;if(e.isLote()&&quantidade<e.getQuantidade()){e.setQuantidade(e.getQuantidade()-quantidade);movimentado=equipamentoService.criarLoteDerivado(e,quantidade,s.getObraDestino(),s.getTecnico(),status,s.getDataSolicitacao(),s.getId());}else{equipamentoService.aplicarDestino(e,s.getObraDestino(),s.getTecnico(),status,s.getDataSolicitacao());}Equipamento loteMovimentado=movimentado;idsAtuais.add(loteMovimentado.getId());Movimentacao m=movimentacoes.findBySolicitacaoIdAndEquipamentoId(s.getId(),loteMovimentado.getId()).orElseGet(()->equipamentoService.novaMovimentacao(loteMovimentado,s,s.getObraOrigem(),s.getObraDestino(),s.getTecnico(),status,s.getDataSolicitacao()));m.reativar();m.setObraOrigem(s.getObraOrigem());m.setObraDestino(s.getObraDestino());m.setTecnico(s.getTecnico());m.setStatus(status);m.setDataMovimentacao(s.getDataSolicitacao());movimentacoes.save(m);}
        for(Movimentacao removida:movimentacoes.findBySolicitacaoId(s.getId()))if(removida.isAtiva()&&!idsAtuais.contains(removida.getEquipamento().getId())){Equipamento e=removida.getEquipamento();equipamentoService.aplicarDestino(e,s.getObraOrigem(),null,s.getObraOrigem()==null?"Em estoque":"Em campo",s.getDataSolicitacao());removida.cancelar();}
    }
    private void reservarMateriais(Solicitacao s){for(MaterialSolicitado material:s.getMateriais()){if(material.getIdentificacao()==null||material.getIdentificacao().isBlank())throw new RegraNegocioException("Todo equipamento movimentado precisa de identificação/série.");Equipamento e=equipamentos.buscarPorSerieParaAtualizacao(material.getIdentificacao()).orElseThrow(()->new RecursoNaoEncontradoException("Equipamento não encontrado pela série: "+material.getIdentificacao()));Long obraAtual=e.getObra()==null?null:e.getObra().getId();Long obraOrigem=s.getObraOrigem()==null?null:s.getObraOrigem().getId();if(!Objects.equals(obraAtual,obraOrigem))throw new RegraNegocioException("O item "+e.getModelo()+" não está na origem informada.");if(!e.isLote()&&material.getQuantidade()!=1)throw new RegraNegocioException("Ativos individuais devem ser movimentados uma unidade por vez.");if(material.getQuantidade()>e.getQuantidadeDisponivel())throw new RegraNegocioException("Quantidade indisponível para "+e.getModelo()+". Disponível: "+e.getQuantidadeDisponivel()+".");e.setQuantidadeReservada(e.getQuantidadeReservada()+material.getQuantidade());}}
    private void liberarReservas(Solicitacao s){for(MaterialSolicitado material:s.getMateriais()){if(material.getIdentificacao()==null)continue;equipamentos.buscarPorSerieParaAtualizacao(material.getIdentificacao()).ifPresent(e->e.setQuantidadeReservada(Math.max(0,e.getQuantidadeReservada()-material.getQuantidade())));}}
    private List<MaterialSolicitado> criarMateriais(List<SolicitacaoDto.MaterialRequisicao> itens){return itens.stream().map(i->new MaterialSolicitado(i.nome(),i.quantidade(),i.identificacao())).toList();}
    private SolicitacaoDto.Resposta resposta(Solicitacao s){return new SolicitacaoDto.Resposta(s.getId(),s.getTipo(),s.getStatus(),s.getSolicitante().getNome(),s.getTecnico().getNome(),s.getObraOrigem()==null?null:s.getObraOrigem().getId(),s.getObraDestino()==null?null:s.getObraDestino().getId(),s.getDataSolicitacao(),s.getDataDecisao(),s.getObservacao(),s.getMateriais().stream().map(m->new SolicitacaoDto.MaterialResposta(m.getId(),m.getNome(),m.getQuantidade(),m.getIdentificacao())).toList());}
}
