ALTER TABLE equipamentos
    ADD COLUMN medida VARCHAR(100),
    ADD COLUMN quantidade INTEGER NOT NULL DEFAULT 1 CHECK (quantidade > 0),
    ADD COLUMN observacoes TEXT;

INSERT INTO equipamentos (tipo, modelo, serie, status, medida, quantidade, observacoes, data_entrada) VALUES
    ('Chaves Combinadas', 'Jogo completo', 'INV-001', 'Em estoque', '9 peças', 1, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Jogo completo', 'INV-002', 'Em estoque', '7 peças', 1, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-003', 'Em estoque', '10 mm', 4, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-004', 'Em estoque', '11 mm', 4, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-005', 'Em estoque', '12 mm', 6, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-006', 'Em estoque', '13 mm', 7, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-007', 'Em estoque', '14 mm', 2, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-008', 'Em estoque', '15 mm', 3, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-009', 'Em estoque', '16 mm', 4, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-010', 'Em estoque', '17 mm', 5, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-011', 'Em estoque', '18 mm', 1, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-012', 'Em estoque', '19 mm', 1, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-013', 'Em estoque', '1/4', 1, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-014', 'Em estoque', '6 mm', 1, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-015', 'Em estoque', '3/8', 1, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-016', 'Em estoque', '8 mm', 1, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-017', 'Em estoque', '9 mm', 1, NULL, CURRENT_DATE),
    ('Chaves Combinadas', 'Chave combinada', 'INV-018', 'Em estoque', '8x9 mm', 1, NULL, CURRENT_DATE),
    ('Chaves Fixas', 'Chave de boca fixa', 'INV-019', 'Em estoque', '15 mm', 1, NULL, CURRENT_DATE),
    ('Chaves Fixas', 'Chave de boca fixa', 'INV-020', 'Em estoque', '19 mm', 1, NULL, CURRENT_DATE),
    ('Chaves Combinadas com Catraca', 'Conjunto', 'INV-021', 'Em estoque', '11 mm a 16 mm', 1, NULL, CURRENT_DATE),
    ('Chaves Biela Tipo L', 'Chave biela', 'INV-022', 'Em estoque', '8 mm', 1, NULL, CURRENT_DATE),
    ('Chaves Biela Tipo L', 'Chave biela', 'INV-023', 'Em estoque', '11 mm', 3, NULL, CURRENT_DATE),
    ('Chaves Biela Tipo L', 'Chave biela', 'INV-024', 'Em estoque', '12 mm', 1, NULL, CURRENT_DATE),
    ('Chaves Biela Tipo L', 'Chave biela', 'INV-025', 'Em estoque', '13 mm', 2, NULL, CURRENT_DATE),
    ('Chaves Biela Tipo L', 'Chave biela', 'INV-026', 'Em estoque', '14 mm', 1, NULL, CURRENT_DATE),
    ('Chaves Biela Tipo L', 'Chave biela', 'INV-027', 'Em estoque', '15 mm', 2, NULL, CURRENT_DATE),
    ('Chaves de Fenda', 'Chave de fenda com catraca', 'INV-028', 'Em estoque', '-', 1, NULL, CURRENT_DATE),
    ('Chave Canhão', 'Chave canhão', 'INV-029', 'Em estoque', '6 mm', 2, NULL, CURRENT_DATE),
    ('Chave Canhão', 'Chave canhão', 'INV-030', 'Em estoque', '8 mm', 1, NULL, CURRENT_DATE),
    ('Chave Canhão', 'Chave canhão', 'INV-031', 'Em estoque', '11 mm', 1, NULL, CURRENT_DATE),
    ('Chave Canhão', 'Chave canhão', 'INV-032', 'Em estoque', '13 mm', 2, NULL, CURRENT_DATE),
    ('Soquetes Magnéticos', 'Soquete magnético', 'INV-033', 'Em estoque', '3/8', 1, 'Para parafusadeira', CURRENT_DATE),
    ('Soquetes Magnéticos', 'Soquete magnético', 'INV-034', 'Em estoque', '5/16', 1, 'Para parafusadeira', CURRENT_DATE),
    ('Soquetes Magnéticos', 'Soquete magnético', 'INV-035', 'Em estoque', '8 mm', 1, 'Para parafusadeira', CURRENT_DATE),
    ('Soquetes Magnéticos', 'Soquete magnético', 'INV-036', 'Em estoque', '10 mm', 1, 'Para parafusadeira', CURRENT_DATE),
    ('Soquetes Magnéticos', 'Soquete magnético', 'INV-037', 'Em estoque', '11 mm', 1, 'Para parafusadeira', CURRENT_DATE),
    ('Pontas', 'Jogo de pontas mini', 'INV-038', 'Em estoque', '-', 2, 'BOSCH e Genérico', CURRENT_DATE),
    ('Alicates', 'Alicate universal', 'INV-039', 'Em estoque', '-', 6, NULL, CURRENT_DATE),
    ('Alicates', 'Alicate de corte', 'INV-040', 'Em estoque', '-', 3, NULL, CURRENT_DATE),
    ('Alicates', 'Alicate de bico pequeno', 'INV-041', 'Em estoque', '-', 3, NULL, CURRENT_DATE),
    ('Alicates', 'Alicate de corte pequeno', 'INV-042', 'Em estoque', '-', 2, NULL, CURRENT_DATE),
    ('Chaves de Fenda', 'Chave de fenda grande', 'INV-043', 'Em estoque', 'G', 4, NULL, CURRENT_DATE),
    ('Chaves de Fenda', 'Chave de fenda média', 'INV-044', 'Em estoque', 'M', 9, NULL, CURRENT_DATE),
    ('Chaves de Fenda', 'Chave de fenda pequena', 'INV-045', 'Em estoque', 'P', 3, NULL, CURRENT_DATE),
    ('Chaves Philips', 'Chave Philips média', 'INV-046', 'Em estoque', 'M', 8, NULL, CURRENT_DATE),
    ('Chaves Philips', 'Chave Philips grande', 'INV-047', 'Em estoque', 'G', 3, NULL, CURRENT_DATE),
    ('Alicates', 'Alicate de compressão', 'INV-048', 'Em estoque', '-', 1, NULL, CURRENT_DATE),
    ('Alicates', 'Alicate de bico médio', 'INV-049', 'Em estoque', 'M', 2, NULL, CURRENT_DATE),
    ('Alicates', 'Alicate de capador de fibras', 'INV-050', 'Em estoque', '-', 1, NULL, CURRENT_DATE),
    ('Alicates', 'Alicate decapa fibra Drop', 'INV-051', 'Em estoque', '-', 1, NULL, CURRENT_DATE),
    ('Alicates', 'Alicate bico de papagaio', 'INV-052', 'Em estoque', '-', 1, NULL, CURRENT_DATE),
    ('Ferramentas', 'Rebitadora', 'INV-053', 'Em estoque', '-', 1, NULL, CURRENT_DATE),
    ('Ferramentas', 'Trena', 'INV-054', 'Em estoque', '5 m', 2, NULL, CURRENT_DATE),
    ('Ferramentas', 'Nível de mão', 'INV-055', 'Em estoque', '-', 2, NULL, CURRENT_DATE),
    ('Ferramentas', 'Punch Down Furukawa', 'INV-056', 'Em estoque', '-', 4, NULL, CURRENT_DATE),
    ('Ferramentas', 'Punch Down Genérico', 'INV-057', 'Em estoque', '-', 9, NULL, CURRENT_DATE),
    ('Alicates', 'Alicate decapador', 'INV-058', 'Em estoque', '-', 1, NULL, CURRENT_DATE),
    ('Alicates', 'Alicate de crimpagem', 'INV-059', 'Em estoque', '-', 5, NULL, CURRENT_DATE),
    ('Alicates', 'Alicate prensa terminais', 'INV-060', 'Em estoque', '-', 2, NULL, CURRENT_DATE),
    ('Brocas Aço Rápido', 'Jogo de brocas', 'INV-061', 'Em estoque', '20 peças', 1, 'Numeração mista', CURRENT_DATE),
    ('Brocas Aço Rápido', 'Jogo de brocas', 'INV-062', 'Em estoque', '15 peças', 2, 'Numeração mista', CURRENT_DATE),
    ('Brocas Madeira', 'Brocas para madeira', 'INV-063', 'Em estoque', 'Mistas', 12, 'Sem numeração específica', CURRENT_DATE),
    ('Brocas Alvenaria', 'Broca', 'INV-064', 'Em estoque', 'S5', 6, NULL, CURRENT_DATE),
    ('Brocas Alvenaria', 'Broca', 'INV-065', 'Em estoque', 'S6', 8, NULL, CURRENT_DATE),
    ('Brocas Alvenaria', 'Broca', 'INV-066', 'Em estoque', 'S8', 11, NULL, CURRENT_DATE),
    ('Brocas Alvenaria', 'Broca', 'INV-067', 'Em estoque', 'S9', 2, NULL, CURRENT_DATE),
    ('Brocas Alvenaria', 'Broca', 'INV-068', 'Em estoque', 'S10', 9, NULL, CURRENT_DATE),
    ('Brocas Alvenaria', 'Broca', 'INV-069', 'Em estoque', 'S14', 3, NULL, CURRENT_DATE),
    ('Brocas Alvenaria', 'Broca', 'INV-070', 'Em estoque', 'S22', 1, NULL, CURRENT_DATE),
    ('Ferramentas', 'Talhadeira redonda', 'INV-071', 'Em estoque', '30 x 250 mm', 1, NULL, CURRENT_DATE),
    ('Maquinário', 'Furadeira Makita', 'INV-072', 'Em estoque', 'Média', 1, 'Sem maleta / 220v', CURRENT_DATE),
    ('Maquinário', 'Furadeira Bosch', 'INV-073', 'Em estoque', 'Pequena', 2, 'Sem maleta', CURRENT_DATE),
    ('Maquinário', 'Furadeira Bosch', 'INV-074', 'Em estoque', 'Media', 3, 'C/ 2 maleta', CURRENT_DATE),
    ('Maquinário', 'Furadeira Skill', 'INV-075', 'Em estoque', 'Media', 1, '220v / verificar funcionamento', CURRENT_DATE),
    ('Maquinário', 'Parafusadeira Bosch', 'INV-076', 'Em estoque', 'Pequena', 2, 'GSR 1000 SMART', CURRENT_DATE),
    ('Maquinário', 'Parafusadeira Bosch', 'INV-077', 'Em estoque', 'Media', 1, 'GSR 120-LI', CURRENT_DATE),
    ('Maquinário', 'Parafusadeira DeWALT', 'INV-078', 'Em estoque', 'Grande', 1, 'Completo', CURRENT_DATE),
    ('Maquinário', 'Parafusadeira EOS', 'INV-079', 'Em estoque', 'Media', 2, 'Apenas 1 completa', CURRENT_DATE),
    ('Maquinário', 'Martelete Bosch c/ fio', 'INV-080', 'Em estoque', 'Grande', 1, 'c/ mandril', CURRENT_DATE),
    ('Maquinário', 'Martelete Bosch', 'INV-081', 'Em estoque', 'Medio', 2, '3 bateria e 1 carregador', CURRENT_DATE),
    ('Maquinário', 'Serra Marmore Makita', 'INV-082', 'Em estoque', 'Medio', 1, 'Sem maleta', CURRENT_DATE),
    ('Maquinário', 'Esmerilhadeira', 'INV-083', 'Em estoque', 'Pequena', 1, NULL, CURRENT_DATE),
    ('Maquinário', 'Aspirador de Pó B&D', 'INV-084', 'Em estoque', 'Pequeno', 1, 'Sem caixa', CURRENT_DATE),
    ('Maquinário', 'Transformador', 'INV-085', 'Em estoque', 'Grande', 2, 'Fio embutido', CURRENT_DATE),
    ('Maquinário', 'Transformador', 'INV-086', 'Em estoque', 'Grande', 1, 'C/ tomada embutida', CURRENT_DATE),
    ('Maquinário', 'Transformador', 'INV-087', 'Em estoque', 'Pequeno', 3, 'C/ tomada embutida', CURRENT_DATE),
    ('Maquinário', 'Rotuladora', 'INV-088', 'Em estoque', 'Grande', 1, 'Defeito', CURRENT_DATE),
    ('Acessorios', 'Bolsa Stanley', 'INV-089', 'Em estoque', 'Pequena', 2, NULL, CURRENT_DATE),
    ('Acessorios', 'Mala de Ferramentas Stanley', 'INV-090', 'Em estoque', 'Grande', 2, NULL, CURRENT_DATE),
    ('Acessorios', 'Mala de Ferramentas Starret', 'INV-091', 'Em estoque', 'Pequena', 1, NULL, CURRENT_DATE),
    ('Acessorios', 'Mala de Ferramentas Irwin', 'INV-092', 'Em estoque', 'Grande', 2, NULL, CURRENT_DATE),
    ('Acessorios', 'Bolsa FLUKE', 'INV-093', 'Em estoque', 'Padrão', 1, 'Bastante marca de uso', CURRENT_DATE);

