export const ROTAS_API = {
  csrf: '/auth/csrf',
  login: '/auth/login',
  logout: '/auth/logout',
  sessao: '/auth/me',
  alterarSenha: '/auth/alterar-senha',
  usuarios: '/usuarios',
  usuario: (usuarioId) => `/usuarios/${usuarioId}`,
  statusUsuario: (usuarioId) => `/usuarios/${usuarioId}/status`,
  redefinirSenhaUsuario: (usuarioId) => `/usuarios/${usuarioId}/redefinicao-senha`,
  resumo: '/painel/resumo',
  obras: '/obras',
  obra: (obraId) => `/obras/${obraId}`,
  arquivamentoObra: (id) => `/obras/${id}/arquivamento`,
  historicoObra: (obraId) => `/obras/${obraId}/historico`,
  inventarioHistoricoObra: (obraId) => `/obras/${obraId}/inventario-historico`,
  equipamentos: '/equipamentos',
  equipamento: (equipamentoId) => `/equipamentos/${equipamentoId}`,
  arquivamentoEquipamento: (id) => `/equipamentos/${id}/arquivamento`,
  movimentacoesEquipamento: (equipamentoId) => `/equipamentos/${equipamentoId}/movimentacoes`,
  historicoEquipamento: (equipamentoId) => `/equipamentos/${equipamentoId}/historico`,
  funcionarios: '/funcionarios',
  funcionario: (funcionarioId) => `/funcionarios/${funcionarioId}`,
  arquivamentoFuncionario: (id) => `/funcionarios/${id}/arquivamento`,
  deposito: '/deposito/equipamentos',
  atividades: '/atividades',
  atividade: (atividadeId) => `/atividades/${atividadeId}`,
  aprovarAtividade: (atividadeId) => `/atividades/${atividadeId}/aprovacao`,
  rejeitarAtividade: (atividadeId) => `/atividades/${atividadeId}/rejeicao`,
  solicitarCompraMaterial: (atividadeId, materialId) => `/atividades/${atividadeId}/materiais/${materialId}/compra`,
  registrarAquisicaoMaterial: (atividadeId, materialId) => `/atividades/${atividadeId}/materiais/${materialId}/aquisicao`,
  distribuirAtividade: (atividadeId) => `/atividades/${atividadeId}/distribuicao`,
  iniciarTransitoAtividade: (atividadeId) => `/atividades/${atividadeId}/transito`,
  concluirAtividade: (atividadeId) => `/atividades/${atividadeId}/conclusao`,
  cautelas: '/cautelas',
};
