export const ROTAS_API = {
  csrf: '/auth/csrf',
  login: '/auth/login',
  logout: '/auth/logout',
  sessao: '/auth/me',
  alterarSenha: '/auth/alterar-senha',
  usuarios: '/usuarios',
  statusUsuario: (usuarioId) => `/usuarios/${usuarioId}/status`,
  redefinirSenhaUsuario: (usuarioId) => `/usuarios/${usuarioId}/redefinicao-senha`,
  resumo: '/painel/resumo',
  obras: '/obras',
  obra: (obraId) => `/obras/${obraId}`,
  cautelaObra: (obraId) => `/obras/${obraId}/cautela`,
  historicoObra: (obraId) => `/obras/${obraId}/historico`,
  equipamentos: '/equipamentos',
  equipamento: (equipamentoId) => `/equipamentos/${equipamentoId}`,
  movimentacoesEquipamento: (equipamentoId) => `/equipamentos/${equipamentoId}/movimentacoes`,
  historicoEquipamento: (equipamentoId) => `/equipamentos/${equipamentoId}/historico`,
  funcionarios: '/funcionarios',
  funcionario: (funcionarioId) => `/funcionarios/${funcionarioId}`,
  deposito: '/deposito/equipamentos',
  atividades: '/atividades',
  atividade: (atividadeId) => `/atividades/${atividadeId}`,
  aprovarAtividade: (atividadeId) => `/atividades/${atividadeId}/aprovacao`,
  rejeitarAtividade: (atividadeId) => `/atividades/${atividadeId}/rejeicao`,
  cautelaAtividade: (atividadeId) => `/atividades/${atividadeId}/cautela`,
};
