import { useState } from 'react';
import { CampoFormulario } from '../field/Field';
import { EstruturaModal } from '../modal-shell/ModalShell';
import estilos from '../nova-obra-modal/NovaObraModal.module.css';

export function ModalNovoUsuario({ funcionarios, aoFechar, aoSalvar }) {
  const [dados, definirDados] = useState({ funcionarioId: '', nome: '', login: '', senhaTemporaria: '', perfil: 'TECNICO' }); const [erro, definirErro] = useState(''); const [salvando, definirSalvando] = useState(false);
  const alterar=(campo,valor)=>definirDados(atual=>({...atual,[campo]:valor}));
  const selecionarFuncionario=(id)=>{const funcionario=funcionarios.find(item=>String(item.id)===id);definirDados(atual=>({...atual,funcionarioId:id,nome:funcionario?.nome||atual.nome,login:funcionario?.email||atual.login}));};
  const salvar=async()=>{definirErro('');definirSalvando(true);try{await aoSalvar({...dados,funcionarioId:dados.funcionarioId?Number(dados.funcionarioId):null,login:dados.login.trim().toLowerCase()});aoFechar();}catch(e){definirErro(e.message);}finally{definirSalvando(false);}};
  const valido=dados.nome.trim()&&dados.login.trim()&&dados.senhaTemporaria.length>=10;
  return <EstruturaModal titulo="Novo usuário" subtitulo="Conceda acesso ao painel e defina as permissões" aoFechar={aoFechar}><div className={estilos.form}><CampoFormulario rotulo="Funcionário vinculado (opcional)"><select className={estilos.input} value={dados.funcionarioId} onChange={(e)=>selecionarFuncionario(e.target.value)}><option value="">Sem vínculo</option>{funcionarios.map(f=><option key={f.id} value={f.id}>{f.nome}</option>)}</select></CampoFormulario><CampoFormulario rotulo="Nome exibido"><input className={estilos.input} value={dados.nome} onChange={(e)=>alterar('nome',e.target.value)}/></CampoFormulario><CampoFormulario rotulo="Login"><input autoComplete="off" className={estilos.input} value={dados.login} onChange={(e)=>alterar('login',e.target.value)}/></CampoFormulario><div className={estilos.grid2}><CampoFormulario rotulo="Perfil"><select className={estilos.input} value={dados.perfil} onChange={(e)=>alterar('perfil',e.target.value)}><option value="TECNICO">Técnico</option><option value="GERENTE">Gerente</option><option value="ADMIN">Administrador</option></select></CampoFormulario><CampoFormulario rotulo="Senha temporária (mínimo 10)"><input type="password" autoComplete="new-password" className={estilos.input} value={dados.senhaTemporaria} onChange={(e)=>alterar('senhaTemporaria',e.target.value)}/></CampoFormulario></div>{erro&&<p role="alert">{erro}</p>}<div className={estilos.actions}><button onClick={aoFechar} className={estilos.cancel}>Cancelar</button><button disabled={!valido||salvando} onClick={salvar} className={estilos.submit}>{salvando?'Salvando...':'Criar usuário'}</button></div></div></EstruturaModal>;
}
