package br.com.era.api.model;
import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.OffsetDateTime;
@Entity @Table(name="equipamentos")
public class Equipamento {
    @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;
    @Column(nullable=false,length=40) private String tipo; @Column(nullable=false,length=180) private String modelo; @Column(nullable=false,unique=true,length=120) private String serie; @Column(nullable=false,length=40) private String status;
    @Column(length=100) private String medida; @Column(nullable=false) private Integer quantidade=1; @Column(name="quantidade_reservada",nullable=false) private Integer quantidadeReservada=0; @Column(name="controle_quantidade",nullable=false,length=20) private String controleQuantidade="INDIVIDUAL"; @Column(columnDefinition="text") private String observacoes;
    @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="obra_id") private Obra obra; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="tecnico_id") private Funcionario tecnico;
    @Column(name="data_entrada") private LocalDate dataEntrada; @Column(name="data_saida") private LocalDate dataSaida;
    @Column(nullable=false) private boolean arquivado=false; @Column(name="arquivado_em") private OffsetDateTime arquivadoEm; @Column(name="arquivado_por",length=120) private String arquivadoPor;
    @Column(name="criado_em",nullable=false) private OffsetDateTime criadoEm; @Column(name="atualizado_em",nullable=false) private OffsetDateTime atualizadoEm;
    public Equipamento() {} @PrePersist void criarDatas(){criadoEm=OffsetDateTime.now();atualizadoEm=criadoEm;} @PreUpdate void atualizarData(){atualizadoEm=OffsetDateTime.now();}
    public Long getId(){return id;} public String getTipo(){return tipo;} public void setTipo(String v){tipo=v;} public String getModelo(){return modelo;} public void setModelo(String v){modelo=v;} public String getSerie(){return serie;} public void setSerie(String v){serie=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public String getMedida(){return medida;} public void setMedida(String v){medida=v;} public Integer getQuantidade(){return quantidade;} public void setQuantidade(Integer v){quantidade=v;} public Integer getQuantidadeReservada(){return quantidadeReservada;} public void setQuantidadeReservada(Integer v){quantidadeReservada=v;} public int getQuantidadeDisponivel(){return quantidade-quantidadeReservada;} public String getControleQuantidade(){return controleQuantidade;} public void setControleQuantidade(String v){controleQuantidade=v;} public boolean isLote(){return "LOTE".equals(controleQuantidade);} public String getObservacoes(){return observacoes;} public void setObservacoes(String v){observacoes=v;} public Obra getObra(){return obra;} public void setObra(Obra v){obra=v;} public Funcionario getTecnico(){return tecnico;} public void setTecnico(Funcionario v){tecnico=v;} public LocalDate getDataEntrada(){return dataEntrada;} public void setDataEntrada(LocalDate v){dataEntrada=v;} public LocalDate getDataSaida(){return dataSaida;} public void setDataSaida(LocalDate v){dataSaida=v;} public boolean isArquivado(){return arquivado;} public void definirArquivamento(boolean v,String autor){arquivado=v;arquivadoEm=v?OffsetDateTime.now():null;arquivadoPor=v?autor:null;}
}
